services:
  - type: web
    name: mine-site
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/config
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: XMR_WALLET
        sync: false
      - key: POOL_HOST
        value: pool.supportxmr.com
      - key: POOL_PORT
        value: "3333"
